export const ROUTES = {
    public: {
      landing: "/",
      main: "/main",
      about: "/about",
      contact: "/contact",
    },
    auth: {
      signIn: "/auth/sign-in",
      register: "/auth/register",
      forgotPassword: "/auth/forgot-password",
      resetPassword: "/auth/reset-password",
      completeProfile: "/auth/complete-profile",
    },
    admin: {
      root: "/admin",
      dashboard: "/admin/dashboard",
    },
    investor: {
      root: "/investor",
      dashboard: "/investor/dashboard",
      profile: "/investor/profile",
      preferences: "/investor/preferences",
      explore: "/investor/explore",
      projectDetails: (projectId: string) => `/investor/explore/${projectId}`,
      interests: "/investor/interests",
      offers: "/investor/offers",
      submitOffer: (projectId: string) => `/investor/offers/submit/${projectId}`,
      offerDetails: (offerId: string) => `/investor/offers/${offerId}`,
      deals: "/investor/deals",
      dealDetails: (dealId: string) => `/investor/deals/${dealId}`,
      chats: "/investor/chats",
      chatDetails: (chatId: string) => `/investor/chats/${chatId}`,
      notifications: "/investor/notifications",
      notificationDetails: (notificationId: string) => `/investor/notifications/${notificationId}`,
    },
    entrepreneur: {
      root: "/entrepreneur",
      dashboard: "/entrepreneur/dashboard",
      profile: "/entrepreneur/profile",
      profileEdit: "/entrepreneur/profile/edit",
      projects: "/entrepreneur/projects",
      createProject: "/entrepreneur/projects/create",
      browseInvestors: "/entrepreneur/browse-investors",
      offers: "/entrepreneur/offers",
      chats: "/entrepreneur/chats",
      notifications: "/entrepreneur/notifications",
    },
  } as const;